name: CI Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Lint with flake8
#        run: flake8
#      - name: docstring coverage
#        run: |
#          docstr-coverage seqteleporter/ --fail-under=100 --badge="./docs_badge.svg"
      - name: Test with python unittest
        run: |
          coverage run -m unittest discover -s tests/
          coverage report -m
#      - name: Generate demo
#        run: |
#          jupyter nbconvert ./demo/seqTeleporter_demo.ipynb --to html --ouput index --output-dir ./